spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mySpringBootPractise
      host: localhost
      port: 27017
      database: mySpringBootPractise
server.port: 8085
management:
  endpoints:
    web:
      exposure:
        include: mappings


mydatabase:
  uri: mongodb://localhost:27017/mySpringBootPractise
  host: localhost
  port: 27017
  database: mySpringBootPractise

studentService:
  getAllStudents:
    uri: http://localhost:8080/v2/students/getAllStudents
  getSingleStudentOnly:
    uri: http://localhost:8080/v1/students/{collegeName}/student
